dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.0.0

# networks:
#   development:
#     host: localhost
#     chainid: 1337  # Choose a suitable chain ID
#     gas_limit: 10000000  # Adjust the gas limit as needed
#     gas_price: 20000000000  # Adjust the gas price as needed

# wallets:
#   from_key: ${YOUR_MNEMONIC_PHRASE}

networks:
  development:
    host: localhost
    port: 8545
    network_id: "*"
  sepolia:
    host:  https://eth-sepolia.g.alchemy.com/v2/QFnGnzjqT2k2WoMImyDd2vrQ6fZeUUTM
    chainid: 11155111
    explorer: https://sepolia.etherscan.io
    account_index: 0
    credentials:
      - account_key_moralis

dotenv: .env
wallets:
  from_key: ${c9d5b954441691c689bcdff41b4f89850dd0af9b17b78123ed03a75c20dd95c0}