dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0


networks:
  default: development    
  development:
    host: localhost
    port: 8545
    network_id: "*"
    cmd_settings:
      accounts: 10
  sepolia:
    host:  https://eth-sepolia.g.alchemy.com/v2/QFnGnzjqT2k2WoMImyDd2vrQ6fZeUUTM
    chainid: 11155111
    explorer: https://sepolia.etherscan.io
    account_index: 0
    credentials:
      - account_key_moralis

dotenv: .env

wallets:
  from_key: ${PRIVATE_KEY}



compiler:
    solc:
        remappings:
          - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"